version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcp_observability
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  hello-world:
    image: mcp/inspector
    pull_policy: always
    build:
      context: ./examples/hello-world
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
